"use client";

import { useEffect,useState } from "react";
import { createPublicClient,http } from "viem";
import { monadTestnet } from "@/lib/config/monad";
import { registryAbi } from "@/lib/monad/registry";
import { hashEvidence } from "@/lib/evidence/canonical";
import type { Evidence } from "@/lib/evidence/schema";

interface ViewData { evidence:Evidence; evidenceRoot:`0x${string}`; transactionHash:`0x${string}`; contractAddress:`0x${string}`; issuer:string; projectId:string; verifiedAt:bigint; status:number; passed:number; total:number; integrity:"valid"|"invalid"; }

export function PublicReceipt({receiptId}:{receiptId:string}){
  const [data,setData]=useState<ViewData|null>(null);const [error,setError]=useState("");
  useEffect(()=>{let cancelled=false;(async()=>{try{const response=await fetch(`/api/receipts/${receiptId}`,{cache:"no-store"});const body=await response.json();if(!response.ok||!body.evidence)throw new Error(body.error||"Evidence unavailable");const evidence=body.evidence.evidence as Evidence;const contractAddress=body.metadata.contractAddress as `0x${string}`;const client=createPublicClient({chain:monadTestnet,transport:http(process.env.NEXT_PUBLIC_MONAD_RPC_URL||"https://testnet-rpc.monad.xyz")});const receipt=await client.readContract({address:contractAddress,abi:registryAbi,functionName:"getReceipt",args:[BigInt(receiptId)]});const computed=hashEvidence(evidence);const integrity=computed.toLowerCase()===receipt.evidenceRoot.toLowerCase()&&computed.toLowerCase()===String(body.evidence.evidenceRoot).toLowerCase()?"valid":"invalid";if(!cancelled)setData({evidence,evidenceRoot:receipt.evidenceRoot,transactionHash:body.metadata.transactionHash,contractAddress,issuer:receipt.issuer,projectId:receipt.projectId,verifiedAt:receipt.verifiedAt,status:receipt.status,passed:receipt.passedChecks,total:receipt.totalChecks,integrity});}catch(cause){if(!cancelled)setError(cause instanceof Error?cause.message:"Evidence unavailable");}})();return()=>{cancelled=true};},[receiptId]);
  if(error)return <div className="panel"><div className="error-box">Evidence unavailable: {error}</div></div>;if(!data)return <div className="panel progress"><span className="spinner"/>Reading evidence and Monad receipt…</div>;
  const labels=["Failed","Partial","Verified","Revoked"];const explorer=process.env.NEXT_PUBLIC_MONAD_EXPLORER_URL||"https://testnet.monadvision.com";return <article className="panel"><div className="result-head"><div><span className="eyebrow">{data.integrity==="valid"?"Evidence integrity: Valid":"Evidence integrity: Invalid"}</span><h2 style={{fontFamily:"Georgia, serif",fontSize:36,margin:"13px 0 3px"}}>{data.evidence.project.name}</h2><p style={{color:"var(--muted)",margin:0}}>{data.evidence.project.repository}</p></div><span className={`status ${labels[data.status]?.toLowerCase()}`}>{labels[data.status]||"Unknown"}</span></div>
  <div className="metric-row"><div className="metric"><strong>{data.passed}</strong><span>Passed</span></div><div className="metric"><strong>{data.total-data.passed}</strong><span>Failed</span></div><div className="metric"><strong>{new Date(Number(data.verifiedAt)*1000).toLocaleString()}</strong><span>Verified at</span></div></div>
  <div className="proof-row"><span>Issuer wallet</span><b className="hash">{data.issuer}</b></div><div className="proof-row"><span>Project identifier</span><b className="hash">{data.projectId}</b></div><div className="proof-row"><span>Selected commit</span><a href={`${data.evidence.project.repository}/commit/${data.evidence.project.commit}`} target="_blank" rel="noreferrer"><b className="hash">{data.evidence.project.commit}</b></a></div><div className="proof-row"><span>Deployment</span><a href={data.evidence.deployment.url} target="_blank" rel="noreferrer"><b>{data.evidence.deployment.url}</b></a></div><div className="proof-row"><span>Registry contract</span><a href={`${explorer}/address/${data.contractAddress}`} target="_blank" rel="noreferrer"><b className="hash">{data.contractAddress}</b></a></div><div className="proof-row"><span>Transaction</span><a href={`${explorer}/tx/${data.transactionHash}`} target="_blank" rel="noreferrer"><b className="hash">{data.transactionHash}</b></a></div>
  <p style={{fontSize:13,color:"var(--muted)",margin:"24px 0 7px"}}>Onchain evidence root</p><div className="hash">{data.evidenceRoot}</div><h3 style={{fontFamily:"Georgia, serif",fontSize:25,marginTop:30}}>Individual checks</h3><div className="check-list">{data.evidence.checks.map(check=><div className="check" key={check.id}><span className={`check-icon ${check.status}`}>{check.status==="passed"?"✓":"!"}</span><div><b>{check.id}</b><p>{check.summary}</p></div><time>{check.durationMs}ms</time></div>)}</div></article>;
}
